services:
  keycloak:
    container_name: worklab-alfa-base-keycloak
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --http-port=8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "30000:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - base-public

  openbao:
    container_name: worklab-alfa-base-openbao
    restart: unless-stopped
    image: openbao/openbao:latest
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=${OPENBAO_DEV_ROOT_TOKEN_ID:-root}
    environment:
      BAO_ADDR: http://0.0.0.0:8200
      BAO_API_ADDR: http://openbao:8200
    ports:
      - "30001:8200"
    volumes:
      - openbao-data:/openbao/file
    networks:
      - base-public

  infisical:
    container_name: worklab-alfa-base-infisical
    restart: unless-stopped
    image: infisical/infisical:v0.158.13
    environment:
      - ENCRYPTION_KEY=f40c9178624764ad85a6830b37ce239a
      - AUTH_SECRET="q6LRi7c717a3DQ8JUxlWYkZpMhG4+RHLoFUVt3Bvo2U="
      - DB_CONNECTION_URI=postgresql://infisical-user:${INFISICAL_POSTGRES_PASSWORD:-infisical}@infisical-postgres:5432/infisical-db
      - REDIS_URL=redis://infisical-redis:6379
      - SITE_URL=http://localhost:30002
    ports:
      - "30002:8080"
    networks:
      - base-public
      - base-internal

  infisical-redis:
    container_name: worklab-alfa-base-infisical-redis
    restart: unless-stopped
    image: redis:7.4.8-alpine3.21
    volumes:
      - infisical-redis-data:/data
    networks:
      - base-internal

  infisical-postgres:
    container_name: worklab-alfa-base-infisical-postgres
    restart: unless-stopped
    image: postgres:16.10-alpine
    environment:
      POSTGRES_DB: infisical-db
      POSTGRES_USER: infisical-user
      POSTGRES_PASSWORD: ${INFISICAL_POSTGRES_PASSWORD:-infisical}
    volumes:
      - infisical-postgres-data:/var/lib/postgresql/data
    networks:
      - base-internal

volumes:
  keycloak-data:
  openbao-data:
  infisical-redis-data:
  infisical-postgres-data:

networks:
  base-public:
  base-internal:
